export interface User {
  id: string;
  name: string;
  avatar: string;
  isCurrentUser: boolean;
}

export interface Comment {
  id: string;
  userId: string;
  text: string;
  timestamp: number;
}

export interface Vlog {
  id: string;
  userId: string;
  videoUrl: string; // Blob URL for local demo
  thumbnailUrl: string;
  duration: number;
  recordedAt: number;
  availableAt: number; // When it "premieres"
  title: string;
  transcription?: string; // Generated by Gemini
  aiSummary?: string; // Generated by Gemini
  comments: Comment[];
  views: number;
}

export interface Group {
  id: string;
  name: string;
  avatar?: string;
  inviteCode: string; // Unique 6-digit code
  members: User[];
  currentVoD: string; // User ID of who is selected today
  vlogs: Vlog[];
  publishTime?: string; // e.g., "09:00"
  recordingStartTime?: string; // e.g., "08:00"
}